### ISSUE TITLE
Pages should be searchable

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#14]
Needs further specification...
- Public vs. Registerspecific?
- Types of content
- Importance, where in roadmap

**Comment by rogsa** [comment]
This is not an obvious choice to have. As i have seen over the past years, more and more sites do not use a general search box, but relies on search engines instead (which can be "localized" to specific sites). We used to have this in Stratum through FTSE (Full-text Search Engine) in SQL Server but we dropped it because it was hard to get it working in every aspect. For example content indexing in PDF, XLS, PPT and so forth, is easier said than done (although FTSE had some support for this). We also realized that it was not used very much, people tend to fall back to Google anyway.

**Comment by frelun** [comment]
I agree with you on this, I rarely use "on site" search tools myself. However I should point out this is me forwarding a requirement from client.
