### ISSUE TITLE
Force https?

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#191]
Force a redirect to https when site is requested through http

**Comment by rogsa** [comment]
Yes, the modern way. Influences [indexing](https://webmasters.googleblog.com/2015/12/indexing-https-pages-by-default.html) and [page ranking](https://webmasters.googleblog.com/2014/08/https-as-ranking-signal.html). No "unsecure" problems when switching back and forth in multiple requests. More and more services demanding this.

**Comment by rogsa** [comment]
Oops! Closed this by mistake. Sorry.

**Comment by gravling** [comment]
No worries but when the question is up, do you have a clear idea of how this is done with IIS?

**Comment by rogsa** [comment]
I think we used the HTTP Redirect Module for this in Stratum earlier but today it is done in our RequestProcessor (a HTTP Module) that is our "request pipeline". Some years ago we did this in Default.aspx (or index.html through JavaScript). Since you have the URL Rewrite Module installed under iisnode I would look there. Found a good reference [here](https://blogs.msdn.microsoft.com/kaushal/2013/05/22/http-to-https-redirects-on-iis-7-x-and-higher/).
