### ISSUE TITLE
Missing role system in keystone

### ISSUE THREAD

**Issue by frelun** [Registercentrum/stratum-cms#2]
There is currently no more than one role in keystone, describing if a user is an admin or not. This makes it more difficult to represent registers as a list representation where some users only will see content related to a specific register.

See 
* github.com/keystonejs/keystone/issues/803
* github.com/keystonejs/keystone/issues/334

This currently favors a way of implementing multiple instances of the same application pointing to different mongo dbs depending on register

**Comment by rogsa** [comment]
In what way will register specific databases solve this issue? In a register, some pages are only visible to logged in users. Today they are actually more specific than that, since they could be restricted to a Register, a Unit or a specific User. This filtering of content could probably be reduced to "logged in to a register or not" if necessary. Higher granularity is probably not needed. 

As i recall, the first thing to do in a new Keystone installation is to create a [User model](http://keystonejs.com/docs/getting-started/#models). If we extend this with a reference to a Stratum Context (through a simple ContextID or perhaps resolved User, Unit and Role id:s), this can be used to opt in content. This reference could be set through an api call to Stratum, upon initialization or per request. This scenario forces the use of https on root level, as will probably be needed anyway to give the user a generic way to log in. The login functionality can be the the one in Stratum. A widget could be used here to handle all aspects of login, or the existing api could be used, at least for BID.

A Page collection in MongoDB, and corresponding model (List) in Keystone, could then have a "register" and a "role" attribute to show in what register a page should be shown an to whom (i now assume this model can be extended in this way).

We should model as few of Stratums entities as possible in Keystone but some loose references are necessary. A reference to Register, at least if we are going to put all registers data in the same database is a must have. Some entities are more static in nature, like Role and Register, so there is probably little damage if these are "hard-coded" in Keystone.

As i see it, the admin role in Keystone is for CMS (ie. non-Stratum) purposes only. All matters concerning Stratum must use the permissions/context sub-system of Stratum.

A whole different approach would be to show all pages to everyone and let all content (widgets a alike) handle the not-logged-in scenario.
